version: 2
jobs:
   build:
     docker:
       - image: opentosca/winery:consistencycheck
     steps:
       - checkout
       - run: git branch
       - run: git status
       - run: ls -la artifacttemplates
       - run: winery --path .
